baseURL = "https://tip.gophercon.is/"
languageCode = "en-us"
title = "GopherCon Iceland"
theme = "hugo-agency-theme"
canonifyurls = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Link custom assets relative to /static
  custom_css = ["/css/custom.css"]
  custom_js  = []
  favicon    = "favicon.ico"
  cfpLink    = "https://www.papercall.io/gophercon-iceland"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [our homepage](/)"

  # Navigation
  [params.navigation]
    brand = "GopherCon Iceland"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    sponsors = "Sponsors"
    speakers = "Speakers"
    schedule = "Schedule"
    venue = "Venue"
    team = "Team"
    contact = "Contact"

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.

    title = "GopherCon Iceland 2018"
    subtitle = "The first European GopherCon"
    buttonLeftText = "Become a speaker"
    buttonLeftLink = "https://www.papercall.io/gophercon-iceland"
    buttonRightText = "Become a sponsor"
    buttonRightLink = "#sponsors"
    content = "Join us on June 1st and 2nd for two days of Go"

  [params.speakers]
    enable = true
    title = "Speakers"
    subtitle = """These are our awesome speakers!<br/>
<a href="https://www.papercall.io/gophercon-iceland">Join them</a> by submitting your talk."""
    contents = ""

  # Schedule section
  [params.schedule]
    enable = true
    title = "Schedule"
    subtitle = ""
    endpoint = "Be part<br>of the<br>story!"

    [[params.schedule.events]]
      img = "1.png"
      date = "May 31st, 2018"
      title = "Training day"
      description = "Come join us for the training sessions, learn Go and a lot more"

    [[params.schedule.events]]
      img = ""
      date = "June 1st, 2018"
      title = "First conference day"
      description = "The conference starts on Friday"

    [[params.schedule.events]]
      img = ""
      date = "June 2nd, 2018"
      title = "The second conference day"
      description = "The conference continues on Saturday"

    [[params.schedule.events]]
      img = ""
      date = "June 3rd, 2018"
      title = "Save the date"
      description = "More details will follow"


  # Team section
  [params.team]
    enable = true
    center = true
    title = "Team"
    subtitle = "The gophers behind this event"

    [[params.team.members]]
      img = "natalie.jpg"
      name = "Natalie Pistunovich"
      scope = []
      social = [
        ["fa-twitter", "https://twitter.com/NataliePis"]
      ]

    [[params.team.members]]
      img = "florin.jpg"
      name = "Florin Pățan"
      social = [
        ["fa-twitter", "https://twitter.com/dlsniper"]
      ]

  [params.sponsors_list]
    enable = true
    center = true
    title = "Sponsors"
    #description = "These are our cool sponsors"
    contents = """Help us make this event even better.<br>Please contact us at "team [at] gophercon [dot] is" for details."""
  
  #[[params.sponsors]]
  #    name = "Your Name here"
  #    logo = "adsa"
  #    link = "#adas"

  [params.venue]
      enable = true
      title = "Venue"
      subtitle = """The conference will take place at <a href="https://en.harpa.is">Harpa</a>"""
      contents = """Harpa is one of Reykjavik‘s greatest and distinguished landmarks.<br/>
It is a cultural and social centre in the heart of the city and features stunning views of the surrounding mountains and the North Atlantic Ocean.<br/>

Harpa's residents are:<br/>
- <a href="https://en.harpa.is/harpa/residents/iceland-symphony-orchestra/">Iceland Symphony Orchestra</a><br/>
- <a href="https://en.harpa.is/harpa/residents/the-icelandic-opera/">The Icelandic Opera</a><br/>
- <a href="https://en.harpa.is/harpa/residents/maximus-musicus/">Maximus Musicus</a><br/>
- <a href="https://en.harpa.is/harpa/residents/the-reykjavik-big-band/">The Reykjavik Big Band</a><br/>

Address: Austurbakki 2, 101 Reykjavík, Iceland<br/>
Image copyright: https://en.harpa.is"""

  # Contact section
  [params.contact]
    enable = true
    formEnabled = false
    title = "Contact us"
    subtitle  = "<br>"
    contents = """If you have any questions, please don't hesitate to contact us at:<br/> "team [at] gophercon [dot] is" """
    email = "team [at] gophercon [dot] is"


  # Footer section
  [params.footer]
    enable = true
    copyrightLeft = "Gopher graphics thanks to <a href='https://github.com/ashleymcnamara/gophers'>Ashley McNamara</a><br>Original theme https://themes.gohugo.io/agency"
    copyrightRight = "Powered by <a href='https://gohugo.io'>Hugo</a><br>&copy; Copyright 2017 Great Tech Events OÜ"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/gopherconeu"
      title = "Twitter"

    #[[params.footer.social]]
    #  icon = "fa-github"
    #  link = "https://github.com/gopherconeu"
    #  title = "Github"

    #[[params.footer.quicklinks]]
    #  text = "Privacy Policy"
    #  link = "/privacy-policy"
    #
    #[[params.footer.quicklinks]]
    #  text = "Code of Conduct"
    #  link = "/code-of-conduct"
