baseURL = "https://localhost:1313/"
#baseURL = "https://tip.gophercon.is/"
#baseURL = "https://gophercon.is/"
languageCode = "en-us"
title = "GopherCon Iceland"
theme = "hugo-agency-theme"
canonifyurls = true


[params]
  # Enter your tracking code to enable Google Analytics
  GoogleAnalytics = "UA-112420901-1"
  name = "Tick Tech Talks UG (haftungsbeschränkt)"

  # Link custom assets relative to /static
  custom_css = ["/css/custom.css"]
  custom_js  = []
  favicon    = "favicon.ico"
  cfpLink    = "https://www.papercall.io/gophercon-iceland"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [our homepage](/)"

  # Navigation
  [params.navigation]
    brand = "GopherCon Iceland"
    # Optional logo as brand stored in img/
    logo = "logo.png"
    schedule = "Schedule"
    speakers = "Speakers"
    mcs = "MCs"
    trainers = "Workshops"
    tickets = "Tickets"
    venue = "Venue"
    sponsors = "Sponsors"
    team = "Team"
    contact = "Contact"
    coc = "Code of Conduct"

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  [params.hero]
    title = "GopherCon Iceland 2018"
    subtitle = "The first European GopherCon<br>May, 31st - June, 3rd"
    buttonLeftText = "Buy your ticket"
    buttonLeftLink = "#buy-ticket"
    buttonRightText = "Become a sponsor"
    buttonRightLink = "#sponsors"
    content = "Join us on June 1st and 2nd for two days of Go"

  [params.speakers]
    enable = true
    title = "Speakers"
    subtitle = """Our conference schedule spans on two days with a single track."""
    contents = ""

  [params.mcs]
    enable = true
    title = "MCs"
    subtitle = """We couldn't have a conference without MCs.<br>
All the pressure of introducing our speakers will rest on their shoulders!"""
    contents = ""

  [params.trainers]
    enable = true
    title = "Workshops"
    subtitle = """Want to learn Go? Or improve your Go skills?<br>
All these training sessions will take place on May 31st.<br>
Attend one of them and learn from the one of the best Gophers!"""
    contents = ""

  [params.tickets]
    enable = true
    title = "Tickets"
    subtitle = """
<a href="https://www.eventbrite.com/e/gophercon-iceland-tickets-45476816382?ref=ebtn" target="_blank"><img src="https://www.eventbrite.com/custombutton?eid=45476816382" alt="Eventbrite - GopherCon Iceland" /></a>
"""
    contents = ""

  [params.schedule]
    enable = true
    title = "Schedule"
    subtitle = ""
    endpoint = "Be part<br>of the<br>story!"

    [[params.schedule.events]]
      img = "1.png"
      date = "May 31st, 2018"
      title = "Training Day"
      description = "Come join us for the training sessions, learn Go and a lot more. <a href='#workshops'>See the workshops</a>."

    [[params.schedule.events]]
      img = "2.png"
      date = "June 1st, 2018"
      title = "Conference Day"
      description = "The conference starts on Friday."

    [[params.schedule.events]]
      img = "2.png"
      date = "June 2nd, 2018"
      title = "Second Conference Day"
      description = "The conference continues on Saturday."

    [[params.schedule.events]]
      img = "1.png"
      date = "June 3rd, 2018"
      title = "Community Day"
      description = "In collaboration with local community."

  [params.team]
    enable = true
    center = true
    title = "Team"
    subtitle = "The gophers behind this event"

  [params.coc]
    enable = true
    title = "Code of Conduct"
    subtitle = """<br>
At GopherCon Europe, we believe that everyone should enjoy the conference, have equal opportunities to learn, and be part of the Go community.<br>
If you encounter any issues preventing you to do this, please contact us at "<b>team [at] gophercon [dot] is</b>" and we'll do our best to help you.<br>
All issues will be anonymous when being dealt with.<br>
<br>
We follow Go's Code of Conduct, to view it, please <a href="https://golang.org/conduct">click here</a>.<br>
<br>
A phone number will be provided for the duration of the conference.<br>
You can also reach us in private on Twitter or at the <a href="https://invite.slack.golangbridge.org/">Gophers Slack</a>:<br>
<ul class="coc-contact">
 <li>Natalie Pistunovich | twitter: <a href="https://twitter.com/nataliepis">@nataliepis</a> | slack: <a href="https://gophers.slack.com/messages/@natalie/">@natalie</a></li>
 <li>Florin Pățan | twitter: <a href="https://twitter.com/dlsniper">@dlsniper</a> | slack: <a href="https://gophers.slack.com/messages/@dlsniper/">@dlsniper</a></li>
</ul>
"""

  [params.sponsors_list]
    enable = true
    center = true
    title = "Sponsors"
    description = "These are our sponsors"
    contents = """Help us make this event even better.<br>Please contact us at "team [at] gophercon [dot] is" for details."""

  [params.venue]
      enable = true
      title = "Venue"
      subtitle = """The conference will take place at <a href="https://en.harpa.is">Harpa</a>"""
      contents = """Harpa is one of Reykjavik‘s greatest and distinguished landmarks.<br/>
It is a cultural and social centre in the heart of the city and features stunning views of the surrounding mountains and the North Atlantic Ocean.<br/>

Harpa's residents are:<br/>
- <a href="https://en.harpa.is/harpa/residents/iceland-symphony-orchestra/">Iceland Symphony Orchestra</a><br/>
- <a href="https://en.harpa.is/harpa/residents/the-icelandic-opera/">The Icelandic Opera</a><br/>
- <a href="https://en.harpa.is/harpa/residents/maximus-musicus/">Maximus Musicus</a><br/>
- <a href="https://en.harpa.is/harpa/residents/the-reykjavik-big-band/">The Reykjavik Big Band</a><br/>

Address: Austurbakki 2, 101 Reykjavík, Iceland<br/>
Image copyright: https://en.harpa.is"""

  # Contact section
  [params.contact]
    enable = true
    formEnabled = false
    title = "Contact us"
    subtitle  = "<br>"
    contents = """If you have any questions, please don't hesitate to contact us at:<br/> "team [at] gophercon [dot] is" """
    email = "team [at] gophercon [dot] is"


  # Footer section
  [params.footer]
    enable = true
    copyrightLeft = "Gopher graphics thanks to <a href='https://github.com/ashleymcnamara/gophers'>Ashley McNamara</a><br>Original theme https://themes.gohugo.io/agency"
    copyrightRight = "Powered by <a href='https://gohugo.io'>Hugo</a><br>&copy; Copyright 2017 Tick Tech Talks UG (haftungsbeschränkt)"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/gopherconeu"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-slack"
      link = "https://gophers.slack.com/messages/gophercon-iceland/"
      title = "Slack"

    #[[params.footer.quicklinks]]
    #  text = "Privacy Policy"
    #  link = "/privacy-policy"
    #
    #[[params.footer.quicklinks]]
    #  text = "Code of Conduct"
    #  link = "/code-of-conduct"
